name: 'Slack Notify'
description: 'Send a job status notification to Slack'
inputs:
  job_name:
    description: The name of the job
  job_status:
    description: The status of the job
  slack_webhook_url:
    description: The Slack webhook URL to use for message delivery
runs:
  using: 'node20'
  main: 'dist/index.js'
